### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [afilio-ti/gtm-afilio-mastertag#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. 

- You should use this method on **_prog_id, type, id_partner_**  when generating the url
var url = ('https://secure.afilio.com.br/mastertag.php?progid=' + 
           prog_id + '&type=' + type + '&id_partner=' + 
           id_partner + '&url_product=' +     
           page_url);

- You should use this method on **_id_category_**  when generating the url
url += '&id_category=' + id_category;

- You should use this method on _**product_id, id_category, product_name, price**_ when generating the url
    url += '&product_id1=' + product_id + '&id_category=' + id_category + '&product_name=' + product_name + '&price=' + price;

- You should use this method on **_product_id, amount_**  when generating the url
    url += '&product_id1=' + product_id + '&amount=' + amount;

- You should use this method on **_amount, transaction_id_** when generating the url
    url += '&amount=' + amount + '&transaction_id=' + transaction_id;

**Comment by johnnickjf** [comment]
Hello! 
 
We made all the updates that you suggested. Could you please check again?
 
Thank you.
